"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'
ENV = os.getenv( 'production',"development")
ALLOWED_HOST = os.getenv('ALLOWED_HOSTS', '').split(',')

CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', '').split(',')
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt', 
    'drf_yasg',
    'api' ,
    'corsheaders'
]
AUTH_USER_MODEL = 'api.CustomUser'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT')
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
MEDIA_URL = "/media/"
STATICFILES_DIRS = [BASE_DIR / "static_files"]
MEDIA_ROOT = BASE_DIR / "media"
STATIC_ROOT = BASE_DIR.parent / "static_files"

STORAGES = {
    "deafault": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "static_files": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES':[
        'rest_framework.authentication.SessionAuthentication',
        #'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication'
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        #Restrección para acceder a los endpoint 
        #'rest_framework.permissions.IsAuthenticated',
        #Hace publicos todos los endpoints por defecto
        'rest_framework.permissions.IsAuthenticated',
    ],
        'DEFAULT_THROTTLE_CLASSES' : [
            # AnnonRateThrottle es una clase de limitación de velocidad para usuarios anónimos
            'rest_framework.throttling.AnonRateThrottle' ,
            # UserRateThrottle es una clase de limitación de velocidad para usuarios autenticados
            'rest_framework.throttling.UserRateThrottle' ,
            ],
        'DEFAULT_THROTTLE_RATES' : {
            'anon': '50000/minute' , # usuarios anónimos: 10 solicitudes por minuto
            'user': '50000/hour' , # usuarios autenticados: 100 por hora
            }

}

#CONFIGURACION JWT-TOKEN
from datetime import timedelta

SIMPLE_JWT = {
    #TOKEN DURE 30 minutos
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), #'00:30:00
}


#CONFIGURACION DE SWAGGER
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer' :{
            'type':'apiKey',
            'description': 'Autenticación por medio de JWT. Ingresear "Bearer <TOKEN>"',
            'name': 'Authorization',
            'in':'header'
        }
    },
    'USE_SESSION_AUTH':False, #Evitar autenticación por basic y por session.
}

###### LOGGING CONFIGURATION ######


#Indico directorio de logs
LOG_DIR = BASE_DIR.parent / '/app/logs'
#En caso de que no exista lo crea
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # Permite usar los loggers de Django
    'formatters':{
        'simple': {'format':"[%(levelname)s] %(name)s: %(message)s"},
        'avanzado': {'format':"[%(levelname)s] %(asctime)s - %(name)s: %(message)s"},
        # "json": {
        #     "()" : "pythonjsonlogger.jsonlogger.JsonFormatter",
        #     "fmt": "%(asctime)s %(levelname)s %(name)s %(message)s "
        #            "%(pathname)s:%(lineno)d %(process)d %(threadName)s"
        # },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',  # muestra los logs en la consola
            'formatter':'simple'
        },
        'file': {
            'class': 'logging.FileHandler', #guardar los logs en archivos
            'filename': LOG_DIR / 'vixel_debug.log',
            'formatter':'avanzado'
        },
        'file_db':{
            'class':'logging.FileHandler',
            #'filename': os.path.join(BASE_DIR, 'aude_academy_log_db.log'),  # guarda en un archivo
            'filename': LOG_DIR / 'db_debug.log',
            'formatter':'avanzado'
        }
    },
    'loggers': {
        'api_vixel': {
            'handlers': ['console', 'file'],
            'level': 'INFO',  # nivel mínimo a registrar
            'propagate': True,
        },
        #Logger por defecto de django que registra todo lo que pasa en la app
        'django':{
            'handlers':['console','file'],
            'level': 'WARNING',
        },
        #Logger por defecto de django para guardar trazabilidad de base de datos
        'django.db.backends':{
            'handlers':['file_db'],
            'level':'DEBUG',
            'propagate': True
        }
    },
}

if ENV == 'production':
    SECURE_SSL_REDIRECT=False
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE=True
    CSRF_COOKIE_SECURE=True

#CONFIGURACION DE EMAIL

#EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
#Se enviaria el correo por smtp
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

#Comentario de email por defecto
DEFAULT_FROM_EMAIL = 'vixel.ventas@gmail.com'
SERVER_EMAIL = 'vixel.ventas@gmail.com'

# Si el backend es SMTP:
EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "1") == "1"
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "0") == "1"
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "10"))  