# Generated by Django 5.2.4 on 2025-11-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pedido_usuario_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
